IK_Project.UI/Areas/Admin/Controllers/CompanyController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.CompanyManagerDTOs;
using IK_Project.Application.Services.AppUserService;
using IK_Project.Application.Services.CompanyService;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyManagerVMs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Data;

namespace IK_Project.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        //private readonly IAppUserService _appUserService;
        IWebHostEnvironment _webHostEnvironment;

        public CompanyController(ICompanyService companyService, IMapper mapper,IWebHostEnvironment webHostEnvironment)
        {
            _companyService = companyService;
            _mapper = mapper;
            _webHostEnvironment= webHostEnvironment;

        }

        public IActionResult Index()
        {
            return View();
        }


        //Aktif Company Listeleme
        public async Task<IActionResult> GetAllActiveCompanies()
        {
            var listDTO = await _companyService.GetDefaults(x => x.Status == Domain.Enums.Status.Active);
            var listVM = _mapper.Map<List<CompanyListVM>>(listDTO);

            return View(listVM);
        }
        public async Task<IActionResult> GetAllCompanies()
        {
            List<CompanyListVM> companyList = _mapper.Map<List<CompanyListVM>>(await _companyService.AllCompanies());
            return View(companyList);

        }

        //Company Ekleme
        [HttpGet]
        public IActionResult Create()
        {
            CompanyCreateVM createVm = new CompanyCreateVM();

            return View(createVm);

        }

        [HttpPost]
        public async Task<IActionResult> Create(CompanyCreateVM vm)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {


                    string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                    string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                    string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                    string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                    string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/images/{tamDosyaAdi}");

                    using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                    {
                        Request.Form.Files[0].CopyTo(fileStream);

                    }

                    vm.Logo = tamDosyaAdi;
                }

                else
                {
                    vm.Logo = vm.Logo;
                }
                try
                {
                    var dto = _mapper.Map<CompanyCreateDTO>(vm);
                    await _companyService.Create(dto);
                    return RedirectToAction("GetAllCompanies");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }
            }
            return View(vm);
        }

        //Delete
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _companyService.Remove(id);
                return RedirectToAction("GetAllActiveCompanies");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("GetAllActiveCompanies");
            }
        }

        //  Category/Details/

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                CompanyUpdateVM company = _mapper.Map<CompanyUpdateVM>(await _companyService.GetById(id));

                return View(company);
                //var dto = _mapper.Map<CompanyListDTO>(id);
                //await _companyService.AllCompanies();
                //var company = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Details(CompanyUpdateVM vm)
        {

            if (Request.Form.Files.Count > 0)
            {


                string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/images/{tamDosyaAdi}");

                using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                {
                    Request.Form.Files[0].CopyTo(fileStream);

                }

                vm.Logo = tamDosyaAdi;
            }

            else
            {
                vm.Logo = vm.Logo;
            }

            var editDto = _mapper.Map<CompanyUpdateDTO>(vm);
            await _companyService.Edit(editDto);
            return RedirectToAction("GetAllCompanies");
        }


        

   
    }




}

IK_Project.UI/Areas/CompanyManager/Controllers/ExpenseController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.ExpenseDTOs;
using IK_Project.Application.Services.CompanyManagerService;
using IK_Project.Application.Services.EmployeeService;
using IK_Project.Application.Services.ExpenseService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.Domain.Enums;
using IK_Project.Infrastructure.Migrations;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using IK_Project.UI.Areas.CompanyManager.Models;
using IK_Project.UI.Areas.CompanyManager.Models.Employee;
using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace IK_Project.UI.Areas.CompanyManager.Controllers
{
    [Area("CompanyManager")]
    [Authorize(Roles = "CompanyManager")]
    public class ExpenseController : Controller

    {

        private readonly UserManager<AppUser> _userManager;
        private readonly IExpenseService _expenseService;
        private readonly IEmployeeService _employeeService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        readonly private ICompanyManagerService _cmService;

        IMapper _mapper;


        public ExpenseController(UserManager<AppUser> userManager, IExpenseService expenseService, IEmployeeService employeeService, IMapper mapper, IWebHostEnvironment webHostEnvironment, ICompanyManagerService cmService)
        {
            _userManager = userManager;
            _expenseService = expenseService;
            _employeeService = employeeService;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _cmService = cmService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CheckExpenseDemands()

        {


            List<CompanyManagerVM> cmVm = _mapper.Map<List<CompanyManagerVM>>(await _cmService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

            var cm = cmVm.FirstOrDefault();

            

            List<ExpenseListVM> expenseList = _mapper.Map<List<ExpenseListVM>>(await _expenseService.GetDefaults(x => x.Employee.CompanyID == cm.CompanyID));
            List<EmployeeListVM> listEmployee = _mapper.Map<List<EmployeeListVM>>(await _employeeService.GetDefaults(x => x.CompanyID == cm.CompanyID));

            

            foreach (var expense in expenseList)
            {
                var demandOwner = _mapper.Map<IK_Project.Domain.Entities.Concrete.Employee>(listEmployee.FirstOrDefault(x => x.Id == expense.EmployeeId));
                expense.Employee = demandOwner;
            }


            return View(expenseList);
        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                ExpenseUpdateVM expense = _mapper.Map<ExpenseUpdateVM>(await _expenseService.GetById(id));

                return View(expense);
                //var dto = _mapper.Map<CompanyListDTO>(id);
                //await _companyService.AllCompanies();
                //var company = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Details(ExpenseUpdateVM vm)
        {

            var expenseDto = _mapper.Map<ExpenseUpdateDTO>(vm);
            await _expenseService.Edit(expenseDto);
            return RedirectToAction("CheckExpenseDemands");
        }




    }
}

IK_Project.UI/Areas/Employee/Controllers/ExpenseController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.CompanyManagerDTOs;
using IK_Project.Application.Models.DTOs.ExpenseDTOs;
using IK_Project.Application.Services.EmployeeService;
using IK_Project.Application.Services.ExpenseService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.Domain.Enums;
using IK_Project.UI.Areas.Admin.Models.ViewModels.AdminVM;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using IK_Project.UI.Areas.CompanyManager.Models.Employee;
using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace IK_Project.UI.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize(Roles = "Employee")]
    public class ExpenseController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IExpenseService _expenseService;
        private readonly IEmployeeService _employeeService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        IMapper _mapper;


        public ExpenseController(UserManager<AppUser> userManager, IExpenseService expenseService, IEmployeeService employeeService, IMapper mapper, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _expenseService = expenseService;
            _employeeService=employeeService;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> GetMyAllExpenses()
        {
            List<EmployeeListVM> employeeListVM = _mapper.Map<List<EmployeeListVM>>(await _employeeService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

            var employee = employeeListVM.FirstOrDefault();


            List<ExpenseListVM> expenseList = _mapper.Map<List<ExpenseListVM>>(await _expenseService.GetDefaults(x=>x.EmployeeId==employee.Id));


            return View(expenseList);
        }


        public async Task<IActionResult> Add()
        {


            List<EmployeeListVM> employeeListVM = _mapper.Map<List<EmployeeListVM>>(await _employeeService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

            var employee = employeeListVM.FirstOrDefault();

            ExpenseCreateVM expenseCreateVM = new()
            {
                EmployeeId = employee.Id,
                AppUserId = employee.AppUserID

            };
            return View(expenseCreateVM);
        }


        [HttpPost]
        public async Task<IActionResult> Add(ExpenseCreateVM vm)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {


                    string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                    string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                    string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                    string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                    string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/expenseFiles/{tamDosyaAdi}");

                    using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                    {
                        Request.Form.Files[0].CopyTo(fileStream);

                    }

                    vm.ExpenseFilePath = tamDosyaAdi;
                }

                else
                {
                    vm.ExpenseFilePath = vm.ExpenseFilePath;
                }

                try
                {
                    List<EmployeeListVM> employeeList = _mapper.Map<List<EmployeeListVM>>(await _employeeService.GetDefaults(x => x.Id == vm.EmployeeId));
                    var employee = employeeList.FirstOrDefault();

                    List<ExpenseListVM> expenses = _mapper.Map<List<ExpenseListVM>>(await _expenseService.GetDefaults(x => x.EmployeeId == vm.EmployeeId));


                    var toplamExpenseConfirm = expenses.Where(x => x.ModifiedDate <= DateTime.Now && x.ModifiedDate >= DateTime.Now.AddYears(-1)  && (x.ConfirmationStatus == ConfirmationStatus.Confirm)).Sum(x => x.Amount);

                    var toplamExpensePending= expenses.Where(x => x.CreatedDate <= DateTime.Now && x.CreatedDate >= DateTime.Now.AddYears(-1) && (x.ConfirmationStatus == ConfirmationStatus.Pending)).Sum(x => x.Amount);


                    //var toplam = db.AddedFoods.Where(u => u.UserID == _gelenUser.ID && u.CreatedDate == DateTime.Today).Sum(x => x.CalculatedKcal);

                    if (toplamExpenseConfirm+toplamExpensePending + vm.Amount > (employee.Salary * 3))
                    {
                        TempData["SalaryError"] = "The amount demanded cannot be more than 3 times your salary in the last one year.";
                        return View(vm);
                    }
                    else
                    {
                        vm.ConfirmationStatus = ConfirmationStatus.Pending;
                        var dto = _mapper.Map<ExpenseCreateDTO>(vm);
                        await _expenseService.Create(dto);
                        return RedirectToAction("GetMyAllExpenses");
                    }


                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }

            }
            return View(vm);

        }


    }
}

IK_Project.UI/Areas/Employee/Views/Expense/Add.cshtml
@using IK_Project.Domain.Enums;
@using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;

@{
    ViewData["Title"] = "Add";
}
@model ExpenseCreateVM
<style>

    /*body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }*/
        .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
    }

    .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
    }

        .closebtn:hover {
            color: black;
        }

    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    * {
        box-sizing: border-box;
    }

    input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=number], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=submit] {
        background-color: #04AA6D;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    /*.container {
            border-radius: 5px;
            background-color: transparent;
            padding: 10px;
        }*/

</style>
<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 3000);
</script>


<div class="container-xl px-4 mt-4">

    <form enctype="multipart/form-data" method="post" asp-action="Add" asp-area="Employee" asp-controller="Expense">

        @if (TempData["SalaryError"] != null)
        {
            <div class="alert" id="alert" role="alert">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                    <strong>Warning!</strong>  @TempData["SalaryError"]
                </div>
        }


        <div class="mb-3">
            <div class="card mb-4 mb-xl-0">
                <div class="card-header" style="font-size:20px">Expense File</div>
                <div class="card-body text-center">

                    <input type="hidden" asp-for="ExpenseFilePath" />
                    <label hidden asp-for="ExpenseFilePath" class="control-label"></label>
                    <input type="file" accept=".pdf, .jpg, .jpeg, .png" asp-for="ExpenseFilePath" class="form-control" />
                    @*<span asp-validation-for="ExpenseFilePath" class="text-danger"></span>*@

                </div>
            </div>
        </div>


        <div class="card mb-4 mb-xl-0">
            <div class="card-header" style="font-size:20px">Expense Details</div>
            <div class="card-body">

                <div class="mb-3">
                    <label style="font-size:16px;" asp-for="ExpenseType" class="small mb-1">Expense Type:</label>
                    <select style="height:max-content; font-size:16px;" asp-for="ExpenseType" asp-items="@Html.GetEnumSelectList<ExpenseType>()"></select>

                </div>


                <div class="mb-3">
                    <label asp-for="Amount" style="font-size:16px;" class="small mb-1" for="form4Example1">Amount:</label>
                    <input style="font-size:16px;" asp-for="Amount" type="number" max="1000000" id="form4Example1" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>


                <div class="mb-3">
                    <label style="font-size:16px;"  for="form4Example1" asp-for="CurrencyUnit" class="small mb-1">Currency Unit:</label>
                    <select style="font-size:16px;" style="height:max-content" asp-for="CurrencyUnit" asp-items="@Html.GetEnumSelectList<CurrecyUnit>()"></select>

                </div>

              <div class="mb-3">
                    <label style="font-size:16px;" class="small mb-1" for="form4Example1">Created Date:</label>
                    
                    <input style="font-size:16px; background-color:lightgrey;" readonly asp-for=CreatedDate id="inputCompany" type="text" value="@DateTime.Now.ToShortDateString()">

                </div>

                <div class="mb-3">
                    <label hidden class="small mb-1" for="form4Example1">EmployeeId:</label>
                    <input hidden readonly asp-for="EmployeeId" id="form4Example1" class="form-control" />
                </div>
                <div class="mb-3">
                    <label hidden class="small mb-1" for="form4Example1">AppUserId:</label>
                    <input hidden readonly asp-for="AppUserId" id="form4Example1" class="form-control" />
                </div>

                <button type="submit" style="font-size:16px;" class="btn btn-primary float-right">Send Expense Demand</button>

            </div>


        </div>







    </form>



</div>

IK_Project.UI/Areas/Employee/Views/Expense/GetMyAllExpenses.cshtml
@using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;

@{
    ViewData["Title"] = "GetMyAllExpenses";
}

@model List<ExpenseListVM>

<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-primary" style="color:azure; font-size:larger" asp-action="Add">Create new expense demand</a>
    </div>

</div>

<br />
<div class="row">
    <div class="col-lg-12">
        <table class="table align-middle mb-0 bg-white">
            <thead class="bg-light">
                <tr>
                    <th>ID</th>
                    <th>Expense Type</th>
                    <th>Amount</th>
                    <th>Currency Unit</th>
                    <th>Confirmation Status</th>
                    <th>Date of Reply</th>
                    <th>Reason Of Rejection</th>
                 @*   <th>Detail</th>
                    <th>Delete</th>*@
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.Id">@item.Id</p>
                            <p class="text-muted mb-0"></p>
                        </td>

                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.ExpenseType">@item.ExpenseType</p>
                            <p class="text-muted mb-0"></p>
                        </td>



                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.Amount">@item.Amount</p>
                            <p class="text-muted mb-0"></p>
                        </td>

                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.CurrencyUnit">@item.CurrencyUnit</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.ConfirmationStatus">@item.ConfirmationStatus</p>
                            <p class="text-muted mb-0"></p>
                        </td>

                        @if (item.DateOfReply != null)
                        {
                            <td>
                                <p class="fw-normal mb-1" asp-for="@item.DateOfReply">@item.DateOfReply.Value.ToShortDateString()</p>
                            </td>
                        }
                        @if (item.ReasonOfRejection != null)
                        {
                            <td>
                                <p class="fw-normal mb-1" asp-for="@item.ReasonOfRejection">@item.ReasonOfRejection</p>
                            </td>
                        }
                    @*    <td>
                            <a asp-action="Details" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-info">
                                Detail
                            </a>
                        </td>*@
                     @*   <td>
                            <a asp-action="Delete" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-danger">
                                Delete
                            </a>
                        </td>
*@



                    </tr>
                }


            </tbody>
        </table>

    </div>
</div>