IK_Project.UI/Areas/Admin/Controllers/CompanyController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.CompanyManagerDTOs;
using IK_Project.Application.Services.AppUserService;
using IK_Project.Application.Services.CompanyService;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyManagerVMs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Data;

namespace IK_Project.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        //private readonly IAppUserService _appUserService;
        IWebHostEnvironment _webHostEnvironment;

        public CompanyController(ICompanyService companyService, IMapper mapper,IWebHostEnvironment webHostEnvironment)
        {
            _companyService = companyService;
            _mapper = mapper;
            _webHostEnvironment= webHostEnvironment;

        }

        public IActionResult Index()
        {
            return View();
        }


        //Aktif Company Listeleme
        public async Task<IActionResult> GetAllActiveCompanies()
        {
            var listDTO = await _companyService.GetDefaults(x => x.Status == Domain.Enums.Status.Active);
            var listVM = _mapper.Map<List<CompanyListVM>>(listDTO);

            return View(listVM);
        }
        public async Task<IActionResult> GetAllCompanies()
        {
            List<CompanyListVM> companyList = _mapper.Map<List<CompanyListVM>>(await _companyService.AllCompanies());
            return View(companyList);

        }

        //Company Ekleme
        [HttpGet]
        public IActionResult Create()
        {
            CompanyCreateVM createVm = new CompanyCreateVM();

            return View(createVm);

        }

        [HttpPost]
        public async Task<IActionResult> Create(CompanyCreateVM vm)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {


                    string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                    string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                    string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                    string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                    string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/images/{tamDosyaAdi}");

                    using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                    {
                        Request.Form.Files[0].CopyTo(fileStream);

                    }

                    vm.Logo = tamDosyaAdi;
                }

                else
                {
                    vm.Logo = vm.Logo;
                }
                try
                {
                    var dto = _mapper.Map<CompanyCreateDTO>(vm);
                    await _companyService.Create(dto);
                    return RedirectToAction("GetAllCompanies");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }
            }
            return View(vm);
        }

        //Delete
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _companyService.Remove(id);
                return RedirectToAction("GetAllActiveCompanies");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("GetAllActiveCompanies");
            }
        }

        //  Category/Details/

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                CompanyUpdateVM company = _mapper.Map<CompanyUpdateVM>(await _companyService.GetById(id));

                return View(company);
                //var dto = _mapper.Map<CompanyListDTO>(id);
                //await _companyService.AllCompanies();
                //var company = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Details(CompanyUpdateVM vm)
        {

            if (Request.Form.Files.Count > 0)
            {


                string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/images/{tamDosyaAdi}");

                using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                {
                    Request.Form.Files[0].CopyTo(fileStream);

                }

                vm.Logo = tamDosyaAdi;
            }

            else
            {
                vm.Logo = vm.Logo;
            }

            var editDto = _mapper.Map<CompanyUpdateDTO>(vm);
            await _companyService.Edit(editDto);
            return RedirectToAction("GetAllCompanies");
        }


        

   
    }




}

IK_Project.UI/Areas/Admin/Controllers/MenuController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.AppRoleDTOs;
using IK_Project.Application.Models.DTOs.MenuDTOs;
using IK_Project.Application.Services.MenuService;
using IK_Project.UI.Areas.Admin.Models.ViewModels.MenuVMs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.RoleVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace IK_Project.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class MenuController : Controller
    {

        private readonly IMenuService _menuService;
        private readonly IMapper _mapper;

        public MenuController(IMenuService menuService, IMapper mapper)
        {
            _menuService = menuService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAllMenus()
        {
            var listDTO = await _menuService.AllMenus();
            var listVM = _mapper.Map<List<MenuListVM>>(listDTO);

            return View(listVM);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MenuCreateVM vm)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    var dto = _mapper.Map<MenuCreateDTO>(vm);
                    await _menuService.Create(dto);
                    return RedirectToAction("GetAllMenus");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }

            }
            return View(vm);
        }


        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _menuService.Remove(id);
                return RedirectToAction("GetAllMenus");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("GetAllMenus");

            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var updateDto = await _menuService.GetById(id);
            var updateVm = _mapper.Map<MenuUpdateVM>(updateDto);

            return View(updateVm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MenuUpdateVM vm)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var updateDto = _mapper.Map<MenuUpdateDTO>(vm);
                    await _menuService.Edit(updateDto);
                    return RedirectToAction("GetAllMenus");
                }
                catch (Exception ex)
                {

                    TempData["error"] = ex.Message;
                }
            }

            return View(vm);
        }


    }
}

IK_Project.UI/Areas/CompanyManager/Controllers/HomeController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.AdminDTOs;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.CompanyManagerDTOs;
using IK_Project.Application.Services.AdminSevice;
using IK_Project.Application.Services.AdvanceService;
using IK_Project.Application.Services.AppUserService;
using IK_Project.Application.Services.CompanyManagerService;
using IK_Project.Application.Services.CompanyService;
using IK_Project.Application.Services.ExpenseService;
using IK_Project.Application.Services.PermissionService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.Domain.Repositories;
using IK_Project.UI.Areas.Admin.Models.ViewModels.AdminVM;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyManagerVMs;
using IK_Project.UI.Areas.CompanyManager.Models;
using IK_Project.UI.Areas.CompanyManager.Models.Employee;
using IK_Project.UI.Areas.Employee.Models.AdvanceVMs;
using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;
using IK_Project.UI.Areas.Employee.Models.PermissionVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IK_Project.UI.Areas.CompanyManager.Controllers
{
    [Area("CompanyManager")]
    [Authorize(Roles ="CompanyManager")]
    public class HomeController : Controller
    {
        readonly private IAppUserService _appUserService;
        readonly private IMapper _mapper;
        readonly private ICompanyManagerService _cmService;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        IWebHostEnvironment _webHostEnvironment;
        IExpenseService _expenseService;
        IAdvanceService _advanceService;
        IPermissionService _permissionService;
        private readonly ICompanyService _companyService;

        public HomeController(IAppUserService appUserService, IMapper mapper, ICompanyManagerService cmService, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment, IExpenseService expenseService,
        IAdvanceService advanceService,
        IPermissionService permissionService, ICompanyService companyService)

        {
            _appUserService = appUserService;
            _mapper = mapper;
            _cmService = cmService;
            _signInManager = signInManager;
            _userManager = userManager;
            this._webHostEnvironment = webHostEnvironment;
            _advanceService = advanceService;
            _expenseService = expenseService;
            _permissionService = permissionService;
            _companyService = companyService;
        }

        public async Task<IActionResult> Index()
        {


            List<CompanyManagerVM> cmVm = _mapper.Map<List<CompanyManagerVM>>(await _cmService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

            var cm = cmVm.FirstOrDefault();


            NotificationVM notificationVM = new NotificationVM();
           List<AdvanceListVM> listAdvance = _mapper.Map<List<AdvanceListVM>>( await _advanceService.GetDefaults(x => x.ConfirmationStatus == Domain.Enums.ConfirmationStatus.Pending && x.Employee.CompanyID == cm.CompanyID));

            List<PermissionListVM> permissionList = _mapper.Map<List<PermissionListVM>>( await _permissionService.GetDefaults(x => x.ConfirmationStatus == Domain.Enums.ConfirmationStatus.Pending && x.Employee.CompanyID == cm.CompanyID));


            List<ExpenseListVM> expenseList = _mapper.Map<List<ExpenseListVM>>(await _expenseService.GetDefaults(x => x.ConfirmationStatus == Domain.Enums.ConfirmationStatus.Pending && x.Employee.CompanyID == cm.CompanyID));

            notificationVM.Advances = listAdvance;
            notificationVM.Permissions = permissionList;
            notificationVM.Expenses = expenseList;
            
            return View(notificationVM);
        }


        [HttpGet]
        public async Task<IActionResult> ProfileDetails()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {

                List<CompanyManagerVM> cmVm = _mapper.Map<List<CompanyManagerVM>>(await _cmService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

                var cm = cmVm.FirstOrDefault();

                List<CompanyListDTO> company = await _companyService.GetDefaults(x => x.Id == cm.CompanyID);

                TempData["companyName"] = company.FirstOrDefault().CompanyName;

                //var userInfo = _mapper.Map<AdminListVM>(await _appUserService.GetByUserName(userName));

                //return View(userInfo);

                return View(cm);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ProfileDetails(CompanyManagerVM vm)
        {

            if (Request.Form.Files.Count > 0)
            {


                string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/images/{tamDosyaAdi}");

                using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                {
                    Request.Form.Files[0].CopyTo(fileStream);

                }

                vm.ProfilePhoto = tamDosyaAdi;
            }

            else
            {
                vm.ProfilePhoto = vm.ProfilePhoto;
            }

            var cmDTO = _mapper.Map<CompanyManagerUpdateDTO>(vm);
            await _cmService.Edit(cmDTO);

            return RedirectToAction("Index", "Home");




        }
    }
}

IK_Project.UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IK_Project.UI.Models;
using IK_Project.Application.Services.MenuService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.UI.Areas.Admin.Models.ViewModels.MenuVMs;
using AutoMapper;

namespace IK_Project.UI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IMenuService _menuService;
    private readonly IMapper _mapper;


    public HomeController(ILogger<HomeController> logger, IMenuService menuService, IMapper mapper)
    {
        _logger = logger;
        _menuService = menuService;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index()
    {
        List<MenuListVM> menuList = _mapper.Map<List<MenuListVM>>(await _menuService.GetDefaults(x => x.Status == Domain.Enums.Status.Active));
        return View(menuList);
    }

    public IActionResult GetOffer()
    {
        return View("GetOffer");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

IK_Project.UI/ViewComponents/AdminViewComponent.cs
using AutoMapper;
using IK_Project.Application.Services.AdminSevice;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.UI.Areas.Admin.Models.ViewModels.AdminVM;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IK_Project.UI.ViewComponents
{
	public class AdminViewComponent : ViewComponent
	{
		IAdminService _adminService;
		IMapper _mapper;
		private readonly SignInManager<AppUser> _signInManager;
		private readonly UserManager<AppUser> _userManager;




		public AdminViewComponent(IAdminService adminService, IMapper mapper, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
		{
			_adminService = adminService;
			_mapper = mapper;
			_signInManager = signInManager;
			_userManager = userManager;

		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			//List<AdminListVM> adminVm = _mapper.Map<List<AdminListVM>>(await _adminService.GetDefaults(x => x.AppUser.UserName == userName));



			//var admin = adminVm.FirstOrDefault();
			////eklenecek unutma!!

			if (_signInManager.IsSignedIn(HttpContext.User))
			{

				List<AdminListVM> adminVm = _mapper.Map<List<AdminListVM>>(await _adminService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

				var admin = adminVm.FirstOrDefault();


				return View(admin);
			}
			else
			{
				return View();






			}







		}
	}
}

IK_Project.UI/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    //Layout = "~Views/Shared/_Layout.cshtml";
}

<style>
    .container3 {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
        background-color: white;
        /*        height: 250px;
             gap: 10px;   */
    }
</style>



<div class="container3">

    @await Component.InvokeAsync("Admin")

</div>

<div class="container3">


    <div class="card" style="width: 18rem;">
        <img src="~/images/work3.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Admin transactions</h5>
            <p class="card-body">Adding Admins are done in this section.</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="Create" asp-area="Admin" asp-controller="Admin">Click</a>
    </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work1.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Company transactions</h5>
            <p class="card-body">Adding, deleting, updating and listing companies are done in this section.</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-primary" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="Company">Click</a>
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work2.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Company Manager transactions</h5>
            <p class="card-body">Adding, deleting, updating and listing Company Managers are done in this section. </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="CompanyManager">Click</a>
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work3.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Package transactions</h5>
            <p class="card-body">Adding, deleting, updating and listing package are done in this section. </p>
        </div>
      
        <div class="card-footer">
            <a class="btn btn-block btn-info" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="Menu">Click</a>
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Role transactions</h5>
            <p class="card-text">Deleting, updating and listing roles are done in this section. </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="Role">Click</a>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <img src="~/images/work2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
            <h5 class="card-title">User-Role transactions</h5>
            <p class="card-text">Adding, deleting, updating and listing roles to the user are done here.</p> 
  </div>
        <div class="card-footer">
            <a class="btn btn-block btn-info" style="color:azure; font-size:larger" asp-action="ListUsers" asp-area="Admin" asp-controller="Role">Click</a>
        </div>
</div>
</div>

IK_Project.UI/Areas/Admin/Views/Home/Login.cshtml
@using IK_Project.UI.Areas.Admin.Models.ViewModels;

@{
    ViewData["Title"] = "Login";
}
@model LoginVM
<style>

  /*  .divider:after,
    .divider:before {
        content: "";
        flex: 1;
        height: 1px;
        background: #eee;
    }
    .h-custom {
            height: calc(100% - 73px);
    }

    input::placeholder {
        font-size: 0.75rem;
    }*/
    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    * {
        box-sizing: border-box;
    }

    input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=password], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }
    input[type=number], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=submit] {
        background-color: darkblue;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: blue ;
        }

    /*.container {
            border-radius: 5px;
            background-color: transparent;
            padding: 10px;
        }*/

</style>
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                     class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form asp-action="Login" method="post">
                    <!-- Email input -->
                    <div class="form-outline mb-4">
                        <label style="font-size:16px;" for="form3Example3">User Name</label>

                        <input style="font-size:16px;" asp-for="UserName" placeholder="Enter User Name" id="form3Example3" type="text" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>

                    <!-- Password input -->
                    <div class="form-outline mb-3">
                        <label style="font-size:16px;" for="form3Example4">Password</label>

                        <input style="font-size:16px;" type="password" asp-for="Password" id="form3Example4" placeholder="Enter password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <div class="d-flex justify-content-between align-items-center">
                        <!-- Checkbox -->
                        <div class="form-check mb-0">
                            <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                            <label style="font-size:16px;"  class="form-check-label" for="form2Example3">
                                Remember me
                            </label>
                        </div>
                        <a style="font-size:16px;" asp-action="PasswordReset" asp-controller="Home" asp-area="Admin" class="text-body">Forgot password?</a>
                    </div>

                    <div class="text-center text-lg-start mt-4 pt-2">
                        <input style="font-size:16px;" type="submit" class="btn btn-block btn-primary" value="Log in" asp-route-Name="@User.Identity.Name" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</section>



@*<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-xl-10">
        <div class="card rounded-3 text-black">
            <div class="row g-0">
                <div class="card-body p-md-5 mx-md-4">
                    <div class="text-center">
                        <img src="~/images/solusan.png"
                             style="width: 300px;" alt="logo">
                        <h4 class="mt-1 mb-5 pb-1"></h4>
                    </div>

                    <form asp-action="Login" method="post">


                        <div class="form-outline mb-4">
                            <label class="form-label" for="form2Example11">User Name:</label>
                            <input id="form2Example11" asp-for="UserName" class="form-control"
                                   placeholder="User Name" />
                        </div>

                        <div class="form-outline mb-4">
                            <label class="form-label" for="form2Example22">Password:</label>
                            <input type="password" asp-for="Password" id="form2Example22" class="form-control" placeholder="Password" />
                        </div>


                        <div class="text-center pt-1 mb-5 pb-1">
                            <input type="submit" class="btn btn-primary btn-block" value="Log in" asp-route-Name="@User.Identity.Name" />
                        </div>

                        <a href="#!" class="text-body">Forgot password?</a>

                        
                        <div class="d-flex align-items-center justify-content-center pb-4">
                        <p class="mb-0 me-2">Hesabınız yok mu?</p>
                        <a asp-action="Register" class="btn btn-outline-danger">Hesap oluştur</a>
                        </div>
                   </form>

                </div>
            </div>


        </div>
    </div>
</div>*@

IK_Project.UI/Areas/Admin/Views/Home/PasswordReset.cshtml
@using IK_Project.UI.Models;

@{
    ViewData["Title"] = "PasswordReset";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.min.js"></script>

@model ResetPasswordViewModel
@if (ViewBag.State == null)
{
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
            <div class="card rounded-3 text-black">
                <div class="row g-0">
                    <div class="card-body p-md-5 mx-md-4">
                        <div class="text-center">
                            <img src="~/images/solusan.png"
                             style="width: 300px;" alt="logo">
                            <h4 class="mt-1 mb-5 pb-1"></h4>
                        </div>

                        <form asp-action="PasswordReset" method="post">


                            <div class="form-outline mb-4">
                                <label class="form-label" for="form2Example11">Email:</label>
                                <input id="form2Example11" asp-for="Email" class="form-control"
                                   placeholder="Write your Email" />
                                   <span asp-validation-for="Email"></span>
                            </div>
                             <div class="text-center pt-1 mb-5 pb-1">
                            <input type="submit" class="btn btn-primary btn-block" value="Send me E-mail" />
                        </div>
                            
                        </form>

                    </div>
                </div>


            </div>
        </div>
    </div>
}

else
{
    if (ViewBag.State)
    {
        <div class="alert-success">Email sent for password request.</div>
    }
    else
    {
        <div class="alert-success">Your e-mail address is not registered in the system.</div>
    }
}