IK_Project.UI/Areas/Admin/Controllers/CompanyController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.CompanyManagerDTOs;
using IK_Project.Application.Services.AppUserService;
using IK_Project.Application.Services.CompanyService;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyManagerVMs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Data;

namespace IK_Project.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        //private readonly IAppUserService _appUserService;
        IWebHostEnvironment _webHostEnvironment;

        public CompanyController(ICompanyService companyService, IMapper mapper,IWebHostEnvironment webHostEnvironment)
        {
            _companyService = companyService;
            _mapper = mapper;
            _webHostEnvironment= webHostEnvironment;

        }

        public IActionResult Index()
        {
            return View();
        }


        //Aktif Company Listeleme
        public async Task<IActionResult> GetAllActiveCompanies()
        {
            var listDTO = await _companyService.GetDefaults(x => x.Status == Domain.Enums.Status.Active);
            var listVM = _mapper.Map<List<CompanyListVM>>(listDTO);

            return View(listVM);
        }
        public async Task<IActionResult> GetAllCompanies()
        {
            List<CompanyListVM> companyList = _mapper.Map<List<CompanyListVM>>(await _companyService.AllCompanies());
            return View(companyList);

        }

        //Company Ekleme
        [HttpGet]
        public IActionResult Create()
        {
            CompanyCreateVM createVm = new CompanyCreateVM();

            return View(createVm);

        }

        [HttpPost]
        public async Task<IActionResult> Create(CompanyCreateVM vm)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {


                    string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                    string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                    string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                    string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                    string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/images/{tamDosyaAdi}");

                    using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                    {
                        Request.Form.Files[0].CopyTo(fileStream);

                    }

                    vm.Logo = tamDosyaAdi;
                }

                else
                {
                    vm.Logo = vm.Logo;
                }
                try
                {
                    var dto = _mapper.Map<CompanyCreateDTO>(vm);
                    await _companyService.Create(dto);
                    return RedirectToAction("GetAllCompanies");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }
            }
            return View(vm);
        }

        //Delete
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _companyService.Remove(id);
                return RedirectToAction("GetAllActiveCompanies");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("GetAllActiveCompanies");
            }
        }

        //  Category/Details/

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                CompanyUpdateVM company = _mapper.Map<CompanyUpdateVM>(await _companyService.GetById(id));

                return View(company);
                //var dto = _mapper.Map<CompanyListDTO>(id);
                //await _companyService.AllCompanies();
                //var company = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Details(CompanyUpdateVM vm)
        {

            if (Request.Form.Files.Count > 0)
            {


                string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/images/{tamDosyaAdi}");

                using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                {
                    Request.Form.Files[0].CopyTo(fileStream);

                }

                vm.Logo = tamDosyaAdi;
            }

            else
            {
                vm.Logo = vm.Logo;
            }

            var editDto = _mapper.Map<CompanyUpdateDTO>(vm);
            await _companyService.Edit(editDto);
            return RedirectToAction("GetAllCompanies");
        }


        

   
    }




}

IK_Project.UI/Areas/CompanyManager/Controllers/PermissionController.cs
using AutoMapper;
using IK_Project.Application.Services.CompanyManagerService;
using IK_Project.Application.Services.EmployeeService;
using IK_Project.Application.Services.ExpenseService;
using IK_Project.Application.Services.PermissionService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.UI.Areas.CompanyManager.Models.Employee;
using IK_Project.UI.Areas.CompanyManager.Models;
using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using IK_Project.UI.Areas.Employee.Models.PermissionVMs;
using IK_Project.Application.Models.DTOs.ExpenseDTOs;
using IK_Project.Application.Models.DTOs.PermissionDTOs;

namespace IK_Project.UI.Areas.CompanyManager.Controllers
{
    [Area("CompanyManager")]
    [Authorize(Roles = "CompanyManager")]
    public class PermissionController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IPermissionService _permissionService;
        private readonly IEmployeeService _employeeService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        readonly private ICompanyManagerService _cmService;

        IMapper _mapper;

        public PermissionController(UserManager<AppUser> userManager, IPermissionService permissionService, IEmployeeService employeeService, IMapper mapper, IWebHostEnvironment webHostEnvironment, ICompanyManagerService cmService)
        {
            _userManager = userManager;
            _permissionService = permissionService;
            _employeeService = employeeService;
            _webHostEnvironment = webHostEnvironment;
            _cmService = cmService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CheckPermissionDemands()
        {
            List<CompanyManagerVM> cmVm = _mapper.Map<List<CompanyManagerVM>>(await _cmService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

            var cm = cmVm.FirstOrDefault();



            List<PermissionListVM> permissionList = _mapper.Map<List<PermissionListVM>>(await _permissionService.GetDefaults(x => x.Employee.CompanyID == cm.CompanyID));
            List<EmployeeListVM> listEmployee = _mapper.Map<List<EmployeeListVM>>(await _employeeService.GetDefaults(x => x.CompanyID == cm.CompanyID)); ;



            foreach (var permission in permissionList)
            {
                var demandOwner = _mapper.Map<IK_Project.Domain.Entities.Concrete.Employee>(listEmployee.FirstOrDefault(x => x.Id == permission.EmployeeId));
                permission.Employee = demandOwner;
            }


            return View(permissionList);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                PermissionUpdateVM permission = _mapper.Map<PermissionUpdateVM>(await _permissionService.GetById(id));

                return View(permission);

            }
        }

        [HttpPost]
        public async Task<IActionResult> Details(PermissionUpdateVM vm)
        {

            var permissionDto = _mapper.Map<PermissionUpdateDTO>(vm);
            await _permissionService.Edit(permissionDto);
            return RedirectToAction("CheckPermissionDemands");
        }

    }
}

IK_Project.UI/Areas/Employee/Controllers/PermissionController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.ExpenseDTOs;
using IK_Project.Application.Models.DTOs.PermissionDTOs;
using IK_Project.Application.Services.EmployeeService;
using IK_Project.Application.Services.ExpenseService;
using IK_Project.Application.Services.PermissionService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.Domain.Enums;
using IK_Project.UI.Areas.CompanyManager.Models.Employee;
using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;
using IK_Project.UI.Areas.Employee.Models.PermissionVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace IK_Project.UI.Areas.Employee.Controllers
{  
        [Area("Employee")]
        [Authorize(Roles = "Employee")]
        public class PermissionController : Controller
        {
            private readonly UserManager<AppUser> _userManager;
            private readonly IPermissionService _permissionService;
            private readonly IEmployeeService _employeeService;
            private readonly IWebHostEnvironment _webHostEnvironment;

            IMapper _mapper;


            public PermissionController(UserManager<AppUser> userManager, IPermissionService permissionService, IEmployeeService employeeService, IMapper mapper, IWebHostEnvironment webHostEnvironment)
            {
                _userManager = userManager;
               _permissionService = permissionService;
                _employeeService = employeeService;
                _mapper = mapper;
                _webHostEnvironment = webHostEnvironment;
            }

            public async Task<IActionResult> GetMyAllPermission()
            {
                List<EmployeeListVM> employeeListVM = _mapper.Map<List<EmployeeListVM>>(await _employeeService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

                var employee = employeeListVM.FirstOrDefault();


                List<PermissionListVM> permissionList = _mapper.Map<List<PermissionListVM>>(await _permissionService.GetDefaults(x => x.EmployeeId == employee.Id));


                return View(permissionList);
            }


            public async Task<IActionResult> Add()
            {


                List<EmployeeListVM> employeeListVM = _mapper.Map<List<EmployeeListVM>>(await _employeeService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

                var employee = employeeListVM.FirstOrDefault();

                PermissionCreateVM permissionCreateVM = new()
                {
                    EmployeeId = employee.Id,
                    AppUserId = employee.AppUserID

                };
                return View(permissionCreateVM);
            }


            [HttpPost]
            public async Task<IActionResult> Add(PermissionCreateVM vm)
            {
                if (ModelState.IsValid)
                {
                    if (Request.Form.Files.Count > 0)
                    {


                        string wwwrootDosyaYolu = _webHostEnvironment.WebRootPath;
                        string dosyaAdi = Path.GetFileNameWithoutExtension(Request.Form.Files[0].FileName);
                        string dosyaUzantisi = Path.GetExtension(Request.Form.Files[0].FileName);
                        string tamDosyaAdi = $"{dosyaAdi}_{Guid.NewGuid()}{dosyaUzantisi}";
                        string yeniDosyaYolu = Path.Combine($"{wwwrootDosyaYolu}/permissionFiles/{tamDosyaAdi}");

                        using (var fileStream = new FileStream(yeniDosyaYolu, FileMode.Create))
                        {
                            Request.Form.Files[0].CopyTo(fileStream);

                        }

                        vm.PermissionFilePath = tamDosyaAdi;
                    }

                    else
                    {
                        vm.PermissionFilePath = vm.PermissionFilePath;
                    }

                    try
                    {
                        vm.ConfirmationStatus = ConfirmationStatus.Pending;
                        var dto = _mapper.Map<PermissionCreateDTO>(vm);
                        await _permissionService.Create(dto);
                        return RedirectToAction("GetMyAllPermission");
                    }
                    catch (Exception ex)
                    {
                        TempData["error"] = ex.Message;
                    }

                }
                return View(vm);

            }
        }
}

IK_Project.UI/Areas/Employee/Views/Permission/Add.cshtml
@using IK_Project.Domain.Enums;
@using IK_Project.UI.Areas.Employee.Models.PermissionVMs;

@{
    ViewData["Title"] = "Add";
}

@model PermissionCreateVM

@*@using (Html.BeginForm())
{
    @Html.LabelFor(m => m.StartDate)
    @Html.TextBoxFor(m => m.StartDate)

    @Html.LabelFor(m => m.EndDate)
    @Html.TextBoxFor(m => m.EndDate)

    <button type="submit">Calculate</button>

    <br />

    @Html.LabelFor(m => m.DateDifference)
    @Html.DisplayFor(m => m.DateDifference)
}*@
<style>

   /* body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }*/
    .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
    }

    .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
    }

        .closebtn:hover {
            color: black;
        }

    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    * {
        box-sizing: border-box;
    }

    input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=date], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=number], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=submit] {
        background-color: #04AA6D;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    /*.container {
            border-radius: 5px;
            background-color: transparent;
            padding: 10px;
        }*/

</style>


<div class="container-xl px-4 mt-4">

    <form enctype="multipart/form-data" method="post" asp-action="Add" asp-area="Employee" asp-controller="Permission">

        <div class="mb-3">
            <div class="card mb-4 mb-xl-0">
                <div class="card-header" style="font-size:20px;">Permission File</div>
                <div class="card-body text-center">

                    <input type="hidden" asp-for="PermissionFilePath" />
                    <label hidden asp-for="PermissionFilePath" class="control-label"></label>
                    <input type="file" accept=".pdf, .jpg, .jpeg, .png" asp-for="PermissionFilePath" class="form-control" />

                </div>
            </div>
        </div>


        <div class="card mb-4 mb-xl-0">
            <div class="card-header" style="font-size:20px">Permission Details</div>
            <div class="card-body">

                <div class="mb-3">
                    <label for="form4Example1" style="font-size:16px;" asp-for="PermissionType" class="small mb-1">Permission Type:</label>
                    <select style="font-size:16px;" style="height:max-content" asp-for="PermissionType" asp-items="@Html.GetEnumSelectList<PermissionType>()" ></select>

                </div>
                <div class="mb-3">
                    <label class="small mb-1" style="font-size:16px;" for="startdate">Start Date:</label>
                    <input type="date" value="@Model.StartDate.ToShortDateString()" asp-for="StartDate" id="StartDate"  />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="small mb-1" style="font-size:16px;" for="enddate">End Date:</label>
                    <input type="date" value="@Model.EndDate.ToShortDateString()" asp-for="EndDate" id="EndDate" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                    <script>
                        var endDate = document.getElementById("EndDate");
                        var startedDate = document.getElementById("StartDate");

                        endDate.addEventListener("change", function () {
                            if (new Date(endDate.value) < new Date(startedDate.value)) {
                                alert("The end day cannot be earlier than the start day.");
                                endDate.value = "";
                            }
                        });
                    </script>
                </div>

                <div class="mb-3">
                    <label class="small mb-1" style="font-size:16px;" for="DateDifference">Number Of Days:</label>
                    <input asp-for="NumberOfDays" type="text" id="datediff" style="background-color:lightgrey;" readonly />
                    <script>
                        function updateDateDifference() {
                            const date1 = new Date(document.getElementById("StartDate").value);
                            const date2 = new Date(document.getElementById("EndDate").value);
                            const diff = ((date2 - date1) / (1000 * 60 * 60 * 24))+1;
                            document.getElementById("datediff").value = diff;
                        }

                        document.getElementById("StartDate").addEventListener("change", updateDateDifference);
                        document.getElementById("EndDate").addEventListener("change", updateDateDifference);
                    </script>
                </div>
             
                <div class="mb-3">
                    <label hidden class="small mb-1" for="form4Example1">EmployeeId:</label>
                    <input readonly hidden asp-for="EmployeeId" id="form4Example1" class="form-control" />
                </div>
                <div class="mb-3">
                    <label hidden class="small mb-1" for="form4Example1">AppUserId:</label>
                    <input readonly hidden asp-for="AppUserId" id="form4Example1" class="form-control" />
                </div>

                <button type="submit" class="btn btn-primary float-right" style="font-size:16px;">Send Permission Demand</button>

            </div>


        </div>
    </form>



</div>

IK_Project.UI/Areas/Employee/Views/Permission/GetMyAllPermission.cshtml
@using IK_Project.UI.Areas.Employee.Models.PermissionVMs;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "GetMyAllPermission";
}

@model List<PermissionListVM>

<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-primary" style="color:azure; font-size:larger" asp-action="Add">Create new permission demand</a>
    </div>

</div>

<br />
<div class="row">
    <div class="col-lg-12">
        <table class="table align-middle mb-0 bg-white">
            <thead class="bg-light">
                <tr>
                    <th>ID</th>
                    <th>Permission Type</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Number Of Days</th>
                    <th>Confirmation Status</th>
                    <th>Date of Reply</th>
                    <th>Reason Of Rejection</th>
                    @*   <th>Detail</th>
                    <th>Delete</th>*@
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.Id">@item.Id</p>
                            <p class="text-muted mb-0"></p>
                        </td>

                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.PermissionType">@item.PermissionType</p>
                            <p class="text-muted mb-0"></p>
                        </td>



                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.StartDate">@item.StartDate.ToShortDateString()</p>
                            <p class="text-muted mb-0"></p>
                        </td>

                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.EndDate">@item.EndDate.ToShortDateString()</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.NumberOfDays">@item.NumberOfDays</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.ConfirmationStatus">@item.ConfirmationStatus</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        @if (item.DateOfReply != null)
                        {
                            <td>
                                <p class="fw-normal mb-1" asp-for="@item.DateOfReply">@item.DateOfReply.Value.ToShortDateString()</p>
                            </td>
                        }
                        @if (item.ReasonOfRejection != null)
                        {
                            <td>
                                <p class="fw-normal mb-1" asp-for="@item.ReasonOfRejection">@item.ReasonOfRejection</p>
                            </td>
                        }
                        @*    <td>
                    <a asp-action="Details" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-info">
                    Detail
                    </a>
                    </td>*@
                        @*   <td>
                    <a asp-action="Delete" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-danger">
                    Delete
                    </a>
                    </td>
                    *@



                    </tr>
                }


            </tbody>
        </table>

    </div>
</div>